I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 40, in script
    hide slendy 1 with fadeout
  File "game/script.rpy", line 40, in <module>
    hide slendy 1 with fadeout
NameError: name 'fadeout' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 40, in script
    hide slendy 1 with fadeout
  File "H:\Contenido de particion\DATOS\RENPY\renpy-8.0.3-sdk\renpy\ast.py", line 1654, in execute
    paired = renpy.python.py_eval(self.paired)
  File "H:\Contenido de particion\DATOS\RENPY\renpy-8.0.3-sdk\renpy\python.py", line 1092, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "H:\Contenido de particion\DATOS\RENPY\renpy-8.0.3-sdk\renpy\python.py", line 1085, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 40, in <module>
    hide slendy 1 with fadeout
NameError: name 'fadeout' is not defined

Windows-10-10.0.19044 AMD64
Ren'Py 8.0.3.22090809
Un hermoso dia 1.0
Sat Apr 15 00:32:36 2023
